name: insultme # you probably want to 'snapcraft register <name>'
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Run randomly to insult yourself # 79 char long summary
description: |
  This is my first snap, I needed something to test, and an insult
  generator seemed fun

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  insultme:
    command: insultme
    plugs: [network-bind]

parts:
  insultme:
    source: .
    plugin: nodejs